<html>
    <head>
        <title>Programación - Pulse by Horizon Festival</title>
        <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="http://kornmexico.com/unirlab02/app/views/css/estilo.css">
   </head>
   <body>
        <div class="contenedor">
            <div class="login-general">
                <div class="login-screen">
                    <span class="titulo">PROGRAMACIÓN</span>
                    <div>
                        <ul>
                            <?php foreach ($programas as $programa): ?>
                            <li>
                                <img width="100" height="100" src="http://kornmexico.com/unirlab02/app/views/css/img/logo.jpg" />
                                <h3><?=$programa["cTema"] ?></h3>
                                <p>Host: <?=$programa["cNombre"]." ".$programa["cApellido"] ?></p>
                                <p>¿Cuándo?: <?=$programa["dFecha"]." a las ".$programa["cHora"] ?><br>
                                    Escúchalo: <a href="<?=$programa["cUrl"] ?>" target="_blank" ><img src="http://kornmexico.com/unirlab02/app/views/css/img/radio.png"></a>
                                </p>
                                <p>
                                    <img src="http://kornmexico.com/unirlab02/app/views/css/img/edit.png">
                                    <img src="http://kornmexico.com/unirlab02/app/views/css/img/delete.png">
                                </p>
                                <div>
                                    <form action="http://kornmexico.com/unirlab02/v1/index.php/programa/update" method="POST" class="login-form validate-form">
                                        <div class="wrapper-inputs validate-input" data-validate = "Este campo es obligatorio">
                                            <input class="input" type="text" maxlength="150" name="tema" placeholder="Tema del programa" value="<?=$programa['cTema']?>" required>
                                        </div>
                                        <div class="wrapper-inputs validate-input" data-validate = "Este campo es obligatorio">
                                            <input class="input" type="url" maxlength="150" name="url" placeholder="Url al programa" value="<?=$programa['cUrl']?>" required>
                                        </div>
                                        <div class="wrapper-inputs validate-input" data-validate = "La fecha es obligatoria">
                                            <input class="input" type="date" name="fecha" placeholder="Fecha" required value="<?=$programa['dFecha']?>">
                                        </div>
                                        <div class="wrapper-inputs validate-input" data-validate = "El horario es obligatorio">
                                            <input class="input" type="time" name="hora" placeholder="Hora" required value="<?=$programa['cHora']?>">
                                        </div>
                                        <div class="container-login-btn">
                                            <button class="login-btn">
                                                Registrar programa
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                        <!--<div class="text-center p-t-136">
                           <a class="txt2" href="controller.php?action=ex">
                              Salir
                              <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                           </a>
                        </div>-->
                    
                </div>
            </div>
        </div>
    </body>
</html>