<html>
   <head>
      <title>Registro - Pulse by Horizon Festival</title>
      <meta charset="UTF-8">
	   <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="http://kornmexico.com/unirlab02/app/views/css/estilo.css">
   </head>
   <body>
      <div class="contenedor">
         <div class="login-general">
            <div class="login-screen">
               <div class="login100-pic js-tilt" data-tilt>
                  <img src="http://kornmexico.com/unirlab02/app/views/css/img/logo.jpg">
               </div>
               <form action="http://kornmexico.com/unirlab02/v1/index.php/user/registrar" method="POST" class="login-form validate-form">
                    <span class="titulo">
                        Registrate
                    </span>
                    <span class="error">
                        <?=$error?>
                    </span>
   
                    <div class="wrapper-inputs validate-input" data-validate = "Este campo es obligatorio">
                        <input class="input" type="text" maxlength="60" name="nombre" placeholder="Nombre" required>
                    </div>
   
                    <div class="wrapper-inputs validate-input" data-validate = "Este campo es obligatorio">
                        <input class="input" type="text" maxlength="60" name="apellidos" placeholder="Apellidos" required>
                    </div>

                    <div class="wrapper-inputs validate-input" data-validate = "Correo inválido">
                        <input class="input" type="email" name="email" placeholder="Email" required>
                    </div>
   
                    <div class="wrapper-inputs validate-input" data-validate = "La contraseña es requerida">
                        <input class="input" type="password" name="pass" placeholder="Password" requireds>
                    </div>

                    <input type="hidden" name="action" value="registrar" />

                    <div class="container-login-btn">
                        <button class="login-btn">
                            Enviar
                        </button>
                    </div>

                    <div class="text-center p-t-136">
                        <a class="txt2" href="http://kornmexico.com/unirlab02/v1">
                            Ya tengo una cuenta
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
               </form>
            </div>
         </div>
      </div>
   </body>
</html>